Repository WattRex/Battery-Cycler-Controller, pull requests merged in 2023-10, with the labels that each got.

#20 Devops
  .github/workflows/deploy_development.yml
  .github/workflows/deploy_production.yml
  .github/workflows/deploy_staging.yml
  .github/workflows/staging_deploy_emulated_bat.yml
  .github/workflows/staging_deploy_real_bat.yml
  code/tests/run_cycler.py
  devops/README.md
  devops/cache_db/createCacheTables.sql
  devops/can/README.md
  devops/can/can_node.py
  devops/can/can_sniffer.service
  devops/cycler/README.md
  devops/cycler/code/requirements.txt
  devops/db_sync/code/requirements.txt
  devops/deploy.sh
  devops/docker/Dockerfile.cycler
  devops/docker/Dockerfile.db_sync
  devops/docker/docker-compose.yml
Labels: enhancement

#13 Mid data
  code/src/wattrex_battery_cycler/mid/mid_data/__init__.py
  code/src/wattrex_battery_cycler/mid/mid_data/mid_data_common.py
  code/src/wattrex_battery_cycler/mid/mid_data/mid_data_devices.py
  code/src/wattrex_battery_cycler/mid/mid_data/mid_data_experiment.py
Labels: enhancement

#22 Create workflow for cycler_datatypes and move code content to cycler …
  .github/workflows/deploy_datatypes.yml
  code/cycler/LICENSE.txt
  code/cycler/MANIFEST.in
  code/cycler/README.md
  code/cycler/pyproject.toml
  code/cycler/requirements.txt
  code/cycler/src/wattrex_battery_cycler/mid/mid_data/__init__.py
  code/cycler/src/wattrex_battery_cycler/mid/mid_data/mid_data_battery.py
  code/cycler/src/wattrex_battery_cycler/mid/mid_data/mid_data_common.py
  code/cycler/src/wattrex_battery_cycler/mid/mid_data/mid_data_devices.py
  code/cycler/src/wattrex_battery_cycler/mid/mid_data/mid_data_experiment.py
  code/cycler/tests/run_cycler.py
Labels: enhancement

#23 Cycler datatypes
  code/datatypes/LICENSE.txt
  code/datatypes/MANIFEST.in
  code/datatypes/README.md
  code/datatypes/pyproject.toml
  code/datatypes/requirements.txt
  code/datatypes/src/comm_data/__init__.py
  code/datatypes/src/comm_data/comm_data.py
  code/datatypes/tests/example.py
Labels: good first issue

#24 Add hello world test to datatypes workflow
  .github/workflows/deploy_datatypes.yml
Labels: enhancement

#25 Cycler datatypes minor changes to test workflow on pull_request
  code/datatypes/tests/example.py
Labels: enhancement

#26 Minor changes to test workflow
  .github/workflows/deploy_datatypes.yml
  code/datatypes/tests/example.py
Labels: documentation

#27 Cycler datatypes
  .github/workflows/deploy_datatypes.yml
Labels: documentation

#28 Cycler datatypes
  .github/workflows/deploy_datatypes.yml
Labels: enhancement

#29 Minor changes
  .github/workflows/deploy_datatypes.yml
  code/datatypes/tests/example.py
Labels: enhancement

#30 Minor documentation changes to test workflow
  .github/workflows/deploy_datatypes.yml
  code/datatypes/tests/example.py
Labels: documentation

#31 Cycler datatypes
  .github/workflows/deploy_datatypes.yml
  code/datatypes/pyproject.toml
  code/datatypes/requirements.txt
  code/datatypes/src/wattrex_battery_cycler_datatypes/comm_data/__init__.py
  code/datatypes/src/wattrex_battery_cycler_datatypes/comm_data/comm_data.py
  code/datatypes/src/wattrex_battery_cycler_datatypes/cycler_data/__init__.py
  code/datatypes/src/wattrex_battery_cycler_datatypes/cycler_data/cycler_data_battery.py
  code/datatypes/src/wattrex_battery_cycler_datatypes/cycler_data/cycler_data_common.py
  code/datatypes/src/wattrex_battery_cycler_datatypes/cycler_data/cycler_data_device.py
  code/datatypes/src/wattrex_battery_cycler_datatypes/cycler_data/cycler_data_experiment.py
  code/datatypes/tests/example.py
Labels: documentation

#33 Add MnCmds to Cycler datatypes/comm_data
  code/datatypes/src/wattrex_battery_cycler_datatypes/comm_data/comm_data.py
Labels: enhancement

#34 Add recently added classes to __init__.py
  code/datatypes/src/wattrex_battery_cycler_datatypes/comm_data/__init__.py
Labels: bug

#36 Minor change in __str__ methods
  code/datatypes/src/wattrex_battery_cycler_datatypes/comm_data/comm_data.py
Labels: enhancement
