Repository WattRex/Battery-Cycler-Controller, pull requests merged in 2023-11, with the labels that each got.

#32 Mid dabs
  .github/workflows/deploy_development.yml
  .github/workflows/stagin_deploy_real_bat.yml
  code/cycler/pyproject.toml
  code/cycler/requirements.txt
  code/cycler/src/wattrex_battery_cycler/mid/mid_dabs/__init__.py
  code/cycler/src/wattrex_battery_cycler/mid/mid_dabs/mid_dabs.py
  code/cycler/tests/test_mid_dabs.py
Labels: good first issue

#42 Staging changes
  .github/workflows/deploy_staging.yml
  .github/workflows/stagin_deploy_real_bat.yml
  .github/workflows/staging_deploy_real_bat.yml
  code/cycler/tests/tests_mid_str.py
  devops/deploy.sh
  devops/docker/Dockerfile.cycler
  devops/docker/Dockerfile.db_sync
  devops/docker/docker-compose.yml
Labels: enhancement

#45 Fix documentation issues
  .github/workflows/deploy_datatypes.yml
  .github/workflows/deploy_development.yml
  .github/workflows/deploy_staging.yml
  .github/workflows/staging_deploy_real_bat.yml
  code/datatypes/src/wattrex_battery_cycler_datatypes/comm_data/comm_data.py
Labels: documentation

#43 Improve of devops process
  .github/workflows/deploy_development.yml
  .github/workflows/staging_deploy_real_bat.yml
  code/cycler/pyproject.toml
  code/cycler/requirements.txt
  code/cycler/tests/test_mid_str.py
  devops/docker/Dockerfile.cycler
Labels: enhancement

#47 cycler data types
  code/datatypes/src/wattrex_battery_cycler_datatypes/cycler_data/cycler_data_device.py
Labels: enhancement

#46 mid dabs
  .github/workflows/deploy_datatypes.yml
  .github/workflows/staging_deploy_real_bat.yml
  .gitignore
  code/cycler/requirements.txt
  code/cycler/src/wattrex_battery_cycler/mid/mid_dabs/mid_dabs.py
  code/cycler/tests/log_config_mid_dabs.yaml
  code/cycler/tests/test_mid_dabs.py
  devops/can/README.md
  devops/can/can_node.py
  devops/can/can_sniffer.service
  devops/can/log_config.yaml
  devops/cycler/README.md
  devops/cycler/code/requirements.txt
  devops/cycler/log_config.yaml
  devops/deploy.sh
  devops/docker/Dockerfile.cycler
  devops/docker/docker-compose.yml
Labels: enhancement

#51 Mid meas
  code/cycler/src/wattrex_battery_cycler/mid/mid_meas/mid_meas.py
  code/cycler/tests/test_mid_meas.py
Labels: enhancement

#44 Mid pwr
  code/cycler/requirements.txt
  code/cycler/src/wattrex_battery_cycler/mid/mid_pwr/__init__.py
  code/cycler/src/wattrex_battery_cycler/mid/mid_pwr/mid_pwr.py
  code/cycler/tests/test_mid_pwr.py
Labels: good first issue

#50 mid str
  code/cycler/src/wattrex_battery_cycler/mid/mid_str/mid_str_facade.py
Labels: enhancement

#52 Change in can_service README.md the env var name to be set at the beg…
  devops/can/README.md
Labels: documentation

#62 Cycler datatypes
  .github/workflows/deploy_datatypes.yml
  code/datatypes/src/wattrex_battery_cycler_datatypes/comm_data/comm_data.py
  code/datatypes/src/wattrex_battery_cycler_datatypes/cycler_data/cycler_data_device.py
  code/datatypes/src/wattrex_battery_cycler_datatypes/cycler_data/cycler_data_experiment.py
Labels: enhancement

#61 mid pwr
  code/cycler/requirements.txt
  code/cycler/src/wattrex_battery_cycler/mid/mid_pwr/mid_pwr.py
  code/cycler/tests/log_config_mid_pwr.yaml
  code/cycler/tests/test_mid_pwr.py
  devops/can/can_node.py
  devops/cycler/Dockerfile.cycler
  devops/cycler/log_config.yaml
  devops/deploy.sh
  devops/docker-compose.yml
Labels: bug

#54 Mid str
  .github/workflows/staging_deploy_real_bat.yml
  code/cycler/src/wattrex_battery_cycler/mid/mid_str/mid_str_cmd.py
  code/cycler/src/wattrex_battery_cycler/mid/mid_str/mid_str_facade.py
  code/cycler/src/wattrex_battery_cycler/mid/mid_str/mid_str_mapping.py
  code/cycler/src/wattrex_battery_cycler/mid/mid_str/mid_str_node.py
  code/cycler/tests/log_config_mid_str.yaml
  code/cycler/tests/test_mid_str.py
  devops/can/config_net.sh
  devops/cycler/Dockerfile.cycler
  devops/deploy.sh
  devops/docker-compose.yml
Labels: enhancement

#66 Change license path in cu_manager and datatypes packages
  .github/workflows/deploy_cu_manager.yml
  .github/workflows/deploy_datatypes.yml
  code/cu_manager/LICENSE.txt
  code/cu_manager/pyproject.toml
  code/cycler/LICENSE.txt
  code/cycler/pyproject.toml
  code/datatypes/LICENSE.txt
  code/datatypes/pyproject.toml
Labels: enhancement

#67 Db sync
  code/db_sync/src/wattrex_battery_cycler_db_sync/db_sync_fachade.py
  code/db_sync/src/wattrex_battery_cycler_db_sync/db_sync_node.py
Labels: bug

#72 db sync
  code/db_sync/src/wattrex_battery_cycler_db_sync/db_sync_fachade.py
Labels: bug

#70 Mid str
  code/cycler/src/wattrex_battery_cycler/mid/mid_str/context.py
  code/cycler/src/wattrex_battery_cycler/mid/mid_str/mid_str_facade.py
  code/cycler/src/wattrex_battery_cycler/mid/mid_str/mid_str_node.py
  code/cycler/tests/test_mid_str.py
Labels: enhancement

#69 Mid meas
  code/cycler/src/wattrex_battery_cycler/mid/mid_meas/context.py
  code/cycler/src/wattrex_battery_cycler/mid/mid_meas/mid_meas.py
  code/cycler/tests/test_mid_meas.py
Labels: enhancement
